name: Use Shared Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-shared:
    uses: stefanpenner-cs/reusable-workflows/.github/workflows/shared.yaml@main
    with:
      ref: main
