name: Use Shared Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-shared:
    uses: stefanpenner-cs/reusable-workflows/.github/workflows/shared.yml@main

  call-no-token:
    uses: stefanpenner-cs/reusable-workflows/.github/workflows/test-no-token.yml@main
