name: Use Shared Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-shared:
    uses: stefanpenner/shared-workflow-test/.github/workflows/shared.yml@main

  call-no-token:
    uses: stefanpenner/shared-workflow-test/.github/workflows/test-no-token.yml@main
